In [1]:
using Pkg
Pkg.activate(".")
using Revise

  Activating project at `~/Workspace/CSC381/projects/dl_f22_project-3-hooded-seal`


In [12]:
includet("activations.jl")
includet("neural_net_training.jl")
includet("generate_data.jl")
includet("plot_models.jl")

In [4]:
(classification_inputs_2d, classification_targets_2d) = generate_classification_data(200, 2; num_clusters=4, lb=-1, ub=1, var=.1, covar=0)

([-0.7200895971047184 1.1792759096280951; -0.2985091962339701 0.6127903152896614; … ; -0.9486254936873102 1.1116790557227758; -0.6450237022712564 1.3050297640819066], [1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [51]:
nn = NeuralNetwork(2, 1, [], sigmoid_activation)
# nn = NeuralNetwork(2, 1, [20], [ReLU_activation, tanh_activation, sigmoid_activation])

NeuralNetwork(Input[Input(NaN), Input(NaN)], Vector{Neuron}[], Neuron[Neuron([0.01403419042855745, -0.01878935998213174], 1.6863475435754416, sigmoid_activation, sigmoid_derivative, NaN, NaN)])

In [11]:
nn.input_layer

2-element Vector{Input}:
 Input(NaN)
 Input(NaN)

In [36]:
M = zeros(2, 5)
M[1, :] = [4, 5, 3, 2, 1]
M

2×5 Matrix{Float64}:
 4.0  5.0  3.0  2.0  1.0
 0.0  0.0  0.0  0.0  0.0

In [64]:
M = [0 5; 9 2]
display(predict(nn, M)
# println(nn.output_layer[1].a)

1×2 Matrix{Float64}:
 0.830954  0.855088

In [22]:
plot_classifier(nn, classification_inputs_2d, classification_targets_2d; resolution=100)

LoadError: unimplemented

In [ ]:
train!(nn, classification_inputs_2d, classification_targets_2d, 0.01, 1000)

In [ ]:
plot_classifier(nn, classification_inputs_2d, classification_targets_2d; resolution=100)

In [3]:
max(0, 10)

10

In [4]:
2^2

4